language: node_js
node_js:
  - "lts/*"
cache: npm
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  keep-history: true
  on:
    branch: master
script:
  - "npm run build"
