language: node_js
node_js:
  - "lts/*"
cache: npm
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  keep_history: true
  on:
    branch: master
script:
  - "npm run build"
